// LifeTracker/
//   Daily/
//     Daily-Root
//     yyyy/
//       Daily-yyyy-Root
//       mm/
//         Daily-yyyy-mm-Root
//         dd/
//           yyyy_mm_dd-Root
//           yyyy_mm_dd-Sport
//           yyyy_mm_dd-Food
//           yyyy_mm_dd-Money

//   Money/
//     Money-Root
//     PlanList/
//       Money-PlanList-Root
//       yyyy/
//         Money-PlanList-yyyy-Root
//         Money-Plan-yyyy_mm_dd__to__yyyy_mm_dd
//     StatsList/
//       Money-StatsList-Root
//       yyyy/
//         Money-StatsList-yyyy-Root
//         Money-Stats-yyyy_mm_dd__to__yyyy_mm_dd

//   Sport/
//     Sport-Root
//     PlanList/
//       Sport-PlanList-Root
//       yyyy/
//         Sport-PlanList-yyyy-Root
//         Sport-Plan-yyyy_mm_dd__to__yyyy_mm_dd
//     StatsList/
//       Sport-StatsList-Root
//       yyyy/
//         Sport-StatsList-yyyy-Root
//         Sport-Stats-yyyy_mm_dd__to__yyyy_mm_dd

//   Food/
//     Food-Root
//     PlanList/
//       Food-PlanList-Root
//       yyyy/
//         Food-PlanList-yyyy-Root
//         Food-Plan-yyyy_mm_dd__to__yyyy_mm_dd
//     StatsList/
//       Food-StatsList-Root
//       yyyy/
//         Food-StatsList-yyyy-Root
//         Food-Stats-yyyy_mm_dd__to__yyyy_mm_dd

//   Library/
//     Library-Root
//     Sport/
//       Library-Sport-Root
//       [NAME]
//     Food/
//       Library-Food-Root
//       [NAME]
//     Money/
//       Library-Money-Root
//       [NAME]
